name: Deploy static page
on: push
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build vue project
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: ./.github/actions/vue-to-github-pages-pnpm
        with:
          username: 'elyse0'
          reponame: 'xielyng'
          token: ${{ secrets.GITHUB_TOKEN }}
